 eureka:
     client:
         serviceUrl:
             defaultZone: http://localhost:8761/eureka/
 server:
     port: 8762

 spring:
     application:
        name: service-helloworld
     datasource:
        name: test
        url: jdbc:oracle:thin:@localhost:1521:otms
        username: 1001
        password: 1001
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.driver.OracleDriver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1 from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

 mybatis:
    mapper-locations: classpath:springcloud/helloworld/dao/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: springcloud.helloworld.model  # 注意：对应实体类的路径